credentials:
  usernames:
    nyambura:
      email: nyamburam12@gmail.com
      logged_in: False # Will be managed automatically
      name: Monica Nyambura
      password: '123456' # Will be hashed automatically
cookie:
  expiry_days: 0
  key: cookie_signature_key # Must be string
  name: cookie_name
preauthorized:
  emails:
    - nyamburam12@gmail.com
users:
  name: Monica
